-- =============================================================
-- Script de Inicialização do Banco de Dados para Supabase
-- Cole isso no SQL Editor do Supabase e clique em "Run"
-- =============================================================

-- 1. Tabela de Perfis (Profiles)
CREATE TABLE IF NOT EXISTS profiles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    bio         VARCHAR(500),
    github_username VARCHAR(100),
    avatar_url  VARCHAR(255),
    linkedin_url VARCHAR(255)
);

-- 2. Tabela de Tecnologias (Technologies)
CREATE TABLE IF NOT EXISTS technologies (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL UNIQUE,
    icon_url VARCHAR(255)
);

-- 3. Tabela de Projetos (Projects)
CREATE TABLE IF NOT EXISTS projects (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(200) NOT NULL,
    description    VARCHAR(500),
    repository_url VARCHAR(255) NOT NULL,
    average_rating DOUBLE PRECISION DEFAULT 0.0,
    upvotes        INTEGER DEFAULT 0,
    profile_id     BIGINT NOT NULL,
    CONSTRAINT fk_projects_profile
        FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);

-- 4. Tabela de Feedbacks
CREATE TABLE IF NOT EXISTS feedbacks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author     VARCHAR(150),
    comment    VARCHAR(500),
    rating     INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    project_id BIGINT NOT NULL,
    CONSTRAINT fk_feedbacks_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

-- 5. Tabela Intermediária — Relacionamento N:N entre Project e Technology
CREATE TABLE IF NOT EXISTS project_technology (
    project_id    BIGINT NOT NULL,
    technology_id BIGINT NOT NULL,
    PRIMARY KEY (project_id, technology_id),
    CONSTRAINT fk_pt_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_technology
        FOREIGN KEY (technology_id) REFERENCES technologies (id) ON DELETE CASCADE
);

-- =============================================================
-- 6. Dados iniciais de tecnologias (opcional)
-- =============================================================
INSERT INTO technologies (name, icon_url) VALUES
('Java',        'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg'),
('Spring Boot', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg'),
('PostgreSQL',  'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg'),
('JavaScript',  'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg'),
('Python',      'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg'),
('React',       'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg'),
('Docker',      'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg')
ON CONFLICT (name) DO NOTHING;
